### ISSUE TITLE
Supporting new ClojureScript 0.0-2665 new REPL

### ISSUE THREAD

**Issue by cigitia** [LightTable/Clojure#38]
[As announced a week ago](https://groups.google.com/forum/#!topic/clojurescript/mRAED4TFlCM), since version 0.0-2665, [ClojureScript has changed its REPL to a Node.js-based one](https://github.com/clojure/clojurescript/wiki/Running-REPLs). This new REPL [caches compilation and analysis to disk](http://swannodette.github.io/2014/12/31/the-old-way-the-new-way/), rather than repeatedly recompiling everything in memory and streaming it to the host process. Are there plans for the Light Table Clojure plugin to support the new REPL?

(Note: Because CIDER for Emacs requires that REPLs using the nREPL protocol, which the new REPL currently does not support out of the box, [CIDER requires manually adding Piggyback to ClojureScript projects](https://github.com/clojure-emacs/cider/issues/939) or using Austin. I’m still unsure whether the Light Table Clojure plugin uses nREPL, but if it does, it may face the same problem.)

**Comment by cldwalker** [comment]
LightTable's repl doesn't depend on the clojurescript repl or recent changes. The main thing we need to do is create an eval for node. We'd like to eventually add this feature but are currently swamped with other tasks. Pull requests are welcome in the meantime. Closing since this enhancement is covered by #7
