### ISSUE TITLE
Split out instarepl to separate plugin

### ISSUE THREAD

**Issue by cldwalker** [LightTable/Clojure#59]
This will require the following:
* [ ] Move https://github.com/LightTable/Clojure/blob/641810a5229153413b46f86e86d408adadddc817/src/lt/plugins/clojure/instarepl.cljs and https://github.com/LightTable/Clojure/blob/master/lein-light-nrepl/src/lighttable/nrepl/sonar.clj to a separate ClojureInstarepl repository
* [ ] Move over instarepl behaviors from clojure.behaviors
* [ ] Depend on Clojure plugin in plugin.edn
* [ ] sonar.clj will be published as its own middleware clojar
    * Will publish this clojar as light-table/lein-light-nrepl-instarepl. Going to start using a light-table maven group so all clojars can be accessible to core team
* [ ]  Add instarepl clojar to [our runner dependencies](https://github.com/LightTable/Clojure/blob/641810a5229153413b46f86e86d408adadddc817/runner/src/leiningen/light_nrepl.clj#L45) so beginners can still use the Instarepl with relative ease. If we give instarepl maintainership to someone else we can remove it. I'm also open to not including instarepl as a dependency but then users would only be able to use instarepl through a [remote connection](https://github.com/LightTable/Clojure#connect-to-remote-nrepl)

**Comment by cldwalker** [comment]
@rundis @kenny-evitt I've made a list of todos for this and will do it soon unless there any objections. I'm curious if anyone has opinions on the last item

**Comment by rundis** [comment]
Sounds like a good plan. 
With regards to the last item on your list, I suspect a lot of people using the instarepl in the first place, probably aren't using remote nrepls, so it's going to be a big downer for them if that was their only option.
I think my preference would be to keep supporting the instarepl plugin through 0.9.x and from 0.10.0 support is ended by the LT Core team. Hopefully by then someone else has picked it up, otherwise ... well tough luck.
